### PR TITLE
:white_check_mark: error(duplicate) in requirement.txt handled

### PR DESCRIPTION
**Pull request by KedarKK1**
error(duplicate) in requirement.txt handled

### CODE REVIEW

**Comment by KedarKK1** [comment]
@Abhinandan-Pal @sbis04 @Theskyspace @vineelsai26 please look into this pull request

**Comment by KedarKK1** [comment]
<h1>Kindly remember to add hackoberfest-accepted label to this Issue & label</h1> otherwise my contribution wont be counted in hactoberfest

**Comment by vineelsai26** [comment]
Before PR
image

After PR

image

Can confirm it solves an issue

**Comment by vineelsai26** [comment]
can you also delete the __pycache__ file you created and create a .gitignore file and add __pycache__ to it so it will not be committed in future 
image

**Comment by KedarKK1** [comment]
> 

Surely ,it solves it I've tested it

**Comment by KedarKK1** [comment]
> can you also delete the **pycache** file you created and create a .gitignore file and add **pycache** to it so it will not be committed in future image

Yes, I'll do that. Thanks @vineelsai26 for your guidance, it's great to see someone helping in a well-meaning way. Happy Hacktoberfest

**Comment by KedarKK1** [comment]
done

**Pull request closed without merging**
